version: '2.0'

services:
  db:
    image: postgres
  koalixcrm:
    image: koalixswitzerland/koalixcrm:1.12.dev20180210
    environment:
      - DJANGO_SETTINGS_MODULE=projectsettings.settings.docker_production_settings
      - JAVA_HOME=/usr/bin/jdk1.8.0_181/jre
    ports:
      - "8000:8000"
    depends_on:
      - db